backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use backend\models\Empresa;
use backend\modules\administracion\models\ChequeCliente;
use backend\modules\contabilidad\models\Compra;
use backend\modules\contabilidad\models\Venta;
use common\helpers\FlashMessageHelpsers;
use common\models\LoginForm;
use Yii;
use yii\data\ArrayDataProvider;
use yii\db\Exception;
use yii\db\Expression;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii\web\Response;

/**
 * Site controller
 */
class SiteController extends BaseController
{

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
	                    'actions' => ['login', 'error', 'error-target', 'get-stat', 'get-chart-data'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     * @throws Exception
     */
    public function actionIndex()
    {
        //Notificaciones del sistema CONTABILIDAD
        if (\Yii::$app->session->has('core_empresa_actual_pc') &&
            \Yii::$app->session->get('core_empresa_actual_pc') != "" &&
	        class_exists('\backend\modules\contabilidad\MainModule')) {
	        $dataProvider = new ArrayDataProvider([
		        'allModels' => $this->getNotifications(),
		        'pagination' => ['pageSize' => 6],
	        ]);

	        $stadistic = $this->getStadistic(true);
        } else
	        $dataProvider = $stadistic = null;

        //En caso de que no haya empresa se redirecciona al create de la misma
        if (!Empresa::find()->exists()) {
            FlashMessageHelpsers::createWarningMessage('No existe ninguna empresa. Por favor cree una.');
            return $this->redirect(['empresa/create']);
        }

        return $this->render('index', [
            'dataProvider' => $dataProvider,
	        'stadistic' => $stadistic,
        ]);
    }

	public function actionGetStat() {
		Yii::$app->response->format = Response::FORMAT_JSON;
		return $this->getStadistic(Yii::$app->request->queryParams['as_json']);
	}

	/**
	 * @param bool $as_json
     * @param string $_pjax
	 * @return array|\Exception|string
	 */
	private function getStadistic($as_json = false, $_pjax = null) {
		try {
			$periodo_contable = Yii::$app->session->get('core_empresa_actual_pc');
			$empresa = Yii::$app->session->get('core_empresa_actual');
			$month = Yii::$app->request->get('month');
            $today = $month ? date('Y-m-t', strtotime("${month}-05")) : date("Y-m-d");
            $first_day = date("Y-m-01", strtotime($today));
            $prev_month_first_day = date("Y-m-01", strtotime($first_day . "-1 months"));
            $prev_month_last_day = date("Y-m-t", strtotime($first_day . "-1 months"));

            $sql = <<<SQL
select fcic.factura_compra_id,
       nro_factura,
       ruc,
       ce.razon_social                           as razon_social,
       monto,
       porcentaje,
       (monto * porcentaje / (100 + porcentaje)) as imp,
       (monto * 100 / (100 + porcentaje))        as grav,
       total
from cont_factura_compra_iva_cuenta_usada as fcic
         left join cont_iva_cuenta as ivacta on fcic.iva_cta_id = ivacta.id
         left join core_iva ci on ivacta.iva_id = ci.id
         left join cont_factura_compra cfc on fcic.factura_compra_id = cfc.id
         left join cont_entidad ce on cfc.entidad_id = ce.id
where
     cfc.periodo_contable_id = $periodo_contable and cfc.empresa_id = $empresa
     and cfc.fecha_emision between [range]
order by porcentaje asc, cfc.id, cfc.nro_factura
SQL;
			$curr_month_qry = preg_replace('/\[range\]/', "'{$first_day}' and '{$today}'", $sql);
			$prev_month_qry = preg_replace('/\[range\]/', "'{$prev_month_first_day}' and '{$prev_month_last_day}'", $sql);

			$result_curr_month = Yii::$app->db->createCommand($curr_month_qry)->queryAll();
			$result_prev_month = Yii::$app->db->createCommand($prev_month_qry)->queryAll();

			$queryResult = ['curr-month' => $result_curr_month, 'prev-month' => $result_prev_month];

			$result = $as_json ? Json::encode($queryResult) : $queryResult;

			return $result;
		} catch (\Exception $exception) {
			return $exception;
		}
	}

    /**
     * @return string
     * @throws Exception
     */
    public function actionGetChartData() {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $periodo_contable = Yii::$app->session->get('core_empresa_actual_pc');
        $empresa = Yii::$app->session->get('core_empresa_actual');
	    $today = date('Y-m-d');
	    $month = explode('-', $today)[1];
	    $year = explode('-', $today)[0];
	    $month_in_text = [
            1 => 'Jan', 2 => 'Feb', 3 => 'Mar', 4 => 'Apr', 5 => 'May', 6 => 'Jun',
            7 => 'Jul', 8 => 'Aug', 9 => 'Sep', 10 => 'Oct', 11 => 'Nov', 12 => 'Dec'
        ];
	    $months_to_use = range(1, $month);
	    $result = [];
	    $result['x'] = [];
	    $result['y'] = [];
        $sql_template = <<<SQL
select fcic.factura_compra_id,
       nro_factura,
       ruc,
       ce.razon_social                           as razon_social,
       monto,
       porcentaje,
       (monto * porcentaje / (100 + porcentaje)) as imp,
       (monto * 100 / (100 + porcentaje))        as grav,
       total
from cont_factura_compra_iva_cuenta_usada as fcic
         left join cont_iva_cuenta as ivacta on fcic.iva_cta_id = ivacta.id
         left join core_iva ci on ivacta.iva_id = ci.id
         left join cont_factura_compra cfc on fcic.factura_compra_id = cfc.id
         left join cont_entidad ce on cfc.entidad_id = ce.id
where
     cfc.periodo_contable_id = $periodo_contable and cfc.empresa_id = $empresa
     and cfc.fecha_emision between [range]
order by porcentaje asc, cfc.id, cfc.nro_factura
SQL;
	    foreach ($months_to_use as $month) {
	        $from = "{$year}-{$month}-01";
	        $to = date('Y-m-t', strtotime($from));

	        $sql = preg_replace('/\[range\]/', "'{$from}' and '{$to}'", $sql_template);
            $resultSet = Yii::$app->db->createCommand($sql)->queryAll();

            array_push($result['x'], $month_in_text[$month]);
            array_push($result['y'], $this->get_gasto($resultSet));
        }

	    return Json::encode($result);
    }

    private function get_gasto($resultSet) {
        $monto = 0.0;
        foreach ($resultSet as $row) {
            $monto += floatval($row['monto']);
        }
        return $monto;
    }

    /**
     * @return array
     * @throws Exception
     */
    private function getNotifications()
    {
        $modelos = array('venta' => 'cont_factura_venta', 'compra' => 'cont_factura_compra');
        $x = 7; //number of days
        $ahora = time();
        $past_stamp = $ahora - $x * 24 * 60 * 60;
        $future_stamp = $ahora + $x * 24 * 60 * 60;
        $hoy = date('Y-m-d', $ahora);
        $desde = date('Y-m-d', $past_stamp);
        $hasta = date('Y-m-d', $future_stamp);

        $resultado = [];

        foreach ($modelos as $key => $value) {
//            $consulta = (new Query())
//                ->select(['id AS id', 'fecha_vencimiento AS vencimiento',
//                    new Expression("'$key' AS tipo"),
//                    new Expression("IF(fecha_vencimiento>= $hoy, 'vencido', 'por vencer') AS estado"),
//                    new Expression("CONCAT('factura: ', nro_factura ) AS detalle")
//
//                ])
//                ->from($value)
//                ->where(['empresa_id' => \Yii::$app->session->get('core_empresa_actual_pc')])
//                ->andWhere(['>=', 'fecha_vencimiento', $desde])
//                ->andWhere(['<=', 'fecha_vencimiento', $hasta])
//                ->indexBy('id')
//                ->createCommand()
//                ->queryAll();
//            $resultado = array_merge($resultado, array_values($consulta));

            $query = ($key == 'compra') ? Compra::find() : Venta::find();
            $query->alias('factura');
	        $query->leftJoin('cont_entidad as entidad', 'factura.entidad_id = entidad.id');
            $tipo = ucfirst($key);
            $modelos = $query->select([
                'factura.id as id',
                'factura.fecha_vencimiento as fecha_vencimiento',
                'factura.estado as estado',
                new Expression("'$tipo' AS tipo"),
                new Expression("IF(fecha_vencimiento <= '$hoy', 'Vencido', 'Por vencer') AS estado"),
	            new Expression(($key == 'compra') ? "CONCAT('Factura: ', nro_factura) AS nro_factura" : "CONCAT('Factura: ',factura.prefijo, ('-'), factura.nro_factura) as nro_factura"),
	            'entidad.razon_social as razon_social',
	            'factura.entidad_id as entidad_id',
	            'factura.saldo as saldo',
            ])
                ->filterWhere(['factura.empresa_id' => Yii::$app->session->get('core_empresa_actual')])
                ->andFilterWhere(['>=', 'factura.fecha_vencimiento', $desde])
                ->andFilterWhere(['<=', 'factura.fecha_vencimiento', $hasta])
	            ->andFilterWhere(['!=', 'factura.saldo', 0])
                ->all();

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\LoginForm;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

backend/views/site/_boxes.php
<?php

/* @var $box_color string */
/* @var $box_type string */
/* @var $iva string */

$box_color = $box_color ? $box_color : 'default';
$box_type = $box_type ? "box-{$box_type}" : '';
?>

<div class="box <?= $box_type ?> box-<?= $box_color ?>">
    <div class="box-header with-border">
        <h3 class="box-title">Default Box Example</h3>
        <div class="box-tools pull-right">
            <!-- Buttons, labels, and many other things can be placed here! -->
            <!-- Here is a label for example -->
            <span class="label label-<?= $box_color ?>"><?= $iva ?></span>
        </div>
        <!-- /.box-tools -->
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        The body of the box
    </div>
    <!-- /.box-body -->
    <!--    <div class="box-footer">-->
    <!--        The footer of the box-->
    <!--    </div>-->
    <!-- box-footer -->
</div>

backend/views/site/_stadistic.php
<?php

use backend\assets\StadisticAsset;
use kartik\datecontrol\DateControl;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\Pjax;
use yiister\adminlte\components\AdminLTE;

/* @var $stadistic array */
/* @var $this View */

StadisticAsset::register($this);
?>

<div class="row">
    <div class="col-lg-3 col-xs-6">
        <?php
        echo '<label class="control-label">Birth Date</label>';
        echo DateControl::widget([
            'type' => DateControl::FORMAT_DATE,
            'ajaxConversion' => false,
            'widgetOptions' => [
                'pluginOptions' => [
                    'orientation' => 'bottom left',
                    'autoclose' => true,
                    'startView' => 'year',
                    'minViewMode' => 'months',
                ]
            ],
            'name' => 'month-gasto',
            'displayFormat' => 'php:M-Y',
            'saveFormat' => 'php:Y-m',
        ]);
        ?>
    </div>
</div>

<br/>

<?php Pjax::begin(['id' => 'chart-pjax']); ?>

<div class="row">
    <div class="col-lg-3 col-xs-6">
        <?=
        yiister\adminlte\widgets\InfoBox::widget(
            [
                "color" => AdminLTE::BG_AQUA,
                "icon" => "fa fa-dollar",
                "text" => "GRAVADAS AL 10%",
                "number" => "0",
                "filled" => true,
                "progress" => 0,
                "progressDescription" => "",
            ]);
        ?>
    </div>
    <div class="col-lg-3 col-xs-6">
        <?=
        yiister\adminlte\widgets\InfoBox::widget(
            [
                "color" => AdminLTE::BG_YELLOW,
                "icon" => "fa fa-dollar",
                "text" => "GRAVADAS AL 5%",
                "number" => "0",
                "filled" => true,
                "progress" => 0,
                "progressDescription" => "",
            ]
        )
        ?>
    </div>
    <div class="col-lg-3 col-xs-6">
        <?=
        yiister\adminlte\widgets\InfoBox::widget(
            [
                "color" => AdminLTE::BG_RED,
                "icon" => "fa fa-dollar",
                "text" => "Exentas",
                "number" => "0",
                "filled" => true,
                "progress" => 0,
                "progressDescription" => "",
            ]
        )
        ?>
    </div>
    <div class="col-lg-3 col-xs-6">
        <?=
        yiister\adminlte\widgets\InfoBox::widget(
            [
                "color" => AdminLTE::BG_GREEN,
                "icon" => "fa fa-dollar",
                "text" => "TOTAL    ",
                "number" => "0",
                "filled" => true,
                "progress" => 0,
                "progressDescription" => "",
            ]
        )
        ?>
    </div>
</div>

<div class="row prev">
    <div class="col-lg-3 col-xs-6">
        <?= $this->render('_boxes', [
            'box_color' => 'info',
            'box_type' => '',
            'iva' => '10%',
        ]) ?>
    </div>
    <div class="col-lg-3 col-xs-6">
        <?= $this->render('_boxes', [
            'box_color' => 'warning',
            'box_type' => '',
            'iva' => '5%',
        ]) ?>
    </div>
    <div class="col-lg-3 col-xs-6">
        <?= $this->render('_boxes', [
            'box_color' => 'danger',
            'box_type' => '',
            'iva' => '0%',
        ]) ?>
    </div>
    <div class="col-lg-3 col-xs-6">
        <?= $this->render('_boxes', [
            'box_color' => 'success',
            'box_type' => '',
            'iva' => 'Total',
        ]) ?>
    </div>
</div>

<?php Pjax::end(); ?>

<div class="row" style="horiz-align: center">
    <div class="col-lg-6 col-xs-6">
        <canvas id="myChart"></canvas>
    </div>
</div>

<script>
    var url = "<?= Url::to(['/site/get-stat']) ?>";
    var char_data_url = "<?= Url::to(['/site/get-chart-data']) ?>";
</script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/error_target.php
<?php
//En caso de error se cierra la ventana extra que se abrió con target blank
$js = <<<JS
window.close();
JS;

$this->registerJs($js);

backend/views/site/index.php
<?php

use yii\helpers\Url;
use kartik\helpers\Html;
use kartik\grid\GridView;
use yiister\adminlte\widgets\Box;
use common\helpers\PermisosHelpers;

/**
 * @var yii\web\View $this
 * @var $stadistic array
 */
$this->title = 'Administracion de sistema';
?>

<?php
$es_admin = PermisosHelpers::requerirMinimoRol('Admin');

echo "<div class='row'>";
// <!--ADMINISTRACIÓN-->
// <!--Solo se agrega si el modulos está presente.-->
//Cheques a cobrar en el sistema de ADMINISTRACIÓN.
/** @var \yii\data\ArrayDataProvider $chequesVencerProvider */
if (class_exists('\backend\modules\administracion\MainModule') &&
    PermisosHelpers::getAcceso('administracion-cheque-cliente-realizar-cobro')) {
    $chequeVencerData = \backend\modules\administracion\models\ChequeCliente::getChequesCobrarDashboard();
    echo $this->renderFile($chequeVencerData[0], ['chequesVencerProvider' => $chequeVencerData[1]]);
}
echo "</div>";

$cards = [];
if ($dataProvider !== null) {
	ob_start();
    Box::begin([
        "header" => "Notificaciones",
	    "type" => Box::TYPE_INFO,
        "filled" => true,
    ]);
    try {
        echo GridView::widget([
            'dataProvider' => $dataProvider,
            'rowOptions' => function ($model) {
                if ($model->estado == 'Vencido') {
                    return ['class' => 'danger'];
                }
                return [];
            },
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'tipo',
                [
                    'attribute' => 'nro_factura',
                    'format' => 'raw',
                    'value' => function ($model) {
                        if (class_exists('\backend\modules\contabilidad\MainModule')) {
                            $url = ($model->tipo == 'Compra') ?
                                Url::to(['contabilidad/compra/view', 'id' => $model->id]) :
                                Url::to(['contabilidad/venta/view', 'id' => $model->id]);
                            return Html::a($model->nro_factura, $url);
                        }
                        return $model->nro_factura;
                    }
                ],
	            [
		            'attribute' => 'razon_social',
		            'format' => 'raw',
		            'value' => function ($model) {
			            if (class_exists('\backend\modules\contabilidad\MainModule')) {
				            $url = Url::to(['contabilidad/entidad/view', 'id' => $model->entidad_id, 'target' => '_blank']);
				            return Html::a($model->razon_social, $url);
			            }
			            return $model->razon_social;
		            },
	            ],
                'estado',
                'fecha_vencimiento:date',
	            [
		            'attribute' => 'saldo',
		            'format' => ['decimal', 0],
		            'hAlign' => 'right',
	            ],
            ],
        ]);
    } catch (Exception $e) {
        echo $e->getMessage();
    }
    Box::end();
    $cards[] = ob_get_clean();
}

// CONTABILIDAD
if (class_exists("\backend\modules\contabilidad\MainModule")) {
    $dataForRender = \backend\modules\contabilidad\models\Prestamo::getDataToRenderFromCore();
    if ($dataForRender['query']->exists()) {
        $today = date("Y-m-d");
        $lastDate = date('Y-m-t');
        $slices = explode('-', $today);
        $slices2 = explode('-', $lastDate);
        $day = (int)$slices[2];
        $lastDay = (int)$slices2[2];
        if ($day <= 5 || $lastDay == $day) {
            ob_start();
            echo $this->renderFile($dataForRender['view'], ['query' => $dataForRender['query']]);
            $cards[] = ob_get_clean();
        }
    }
}

$cant_card = sizeof($cards);
$rows = ceil($cant_card / 3);
$last_card = $cant_card % 3;
$col = ($cant_card == 0 ? (12 / 3) : (12 / $cant_card));
$last_card_col = ($last_card > 0) ? (12 / $last_card) : 12;
$i = 1;
$row_clossed = true;
foreach ($cards as $k => $card) {
    if ($i <= $rows && $row_clossed) {
        $row_clossed = false;
        echo "<div class='row'>";
        $i++;
    }
    if ($k < ($cant_card - $last_card))
        echo "<div class='col-lg-{$col} col-xs-6'>";
    else {
        echo "<div class='col-lg-{$last_card_col} col-xs-6'>";
    }
    echo $card;
    echo "</div>";
    if (($k + 1) % 3 == 0) {
        $row_clossed = true;
        echo "</div>";
    }
}

if (!$row_clossed) {
    echo "</div>";
}

if (class_exists('\backend\modules\calendario\MainModule')) {
    echo backend\modules\calendario\helpers\CalendarioViewHelper::NotificationsForCalendario();
}

echo is_null($stadistic) ? '' : $this->render('_stadistic', ['stadistic' => $stadistic]);
?>
    <div class="body-content"></div>
<?php
$url = Url::to(['/session/set-empresa-actual']);

$script = <<<JS
$( document ).ready(function() {
     $.get(
        "$url",
        function (data) {
            $('.modal-body').html(data);
            $('#modal').modal();
            $('.modal-header').css('background', '#3c8dbc'); //Color del header
            $('.modal-title').html("Seleccione una empresa para trabajar"); // Título para el header del modal
        }
     )
});
JS;

if (Yii::$app->session->get('core_empresa_actual') === null) {
    $this->registerJs($script);
}

$js = <<<JS
$(document).on('click', '.tiene_modal', (function () {
    let boton = $(this);
    let title = boton.attr('title');
    let boton_id = boton.attr('id');
    let url = boton.data('url');
    $.get(
        url,
        function (data) {
            if (data !== "") {
                let modal = $(boton.data('target'));
                $('.modal-body', modal).html(data);
                $('.modal-header', modal).css('background', '#3c8dbc');
                $('.modal-title', modal).html(title);
                modal.modal();
            } else {
                $.pjax.reload({container: "#flash_message_id", async: false});
                $("#modal").modal("hide");
                $("modal-body").html("");
            }
        }
    );
}));
JS;

$this->registerJs($js);
?>

backend/views/site/login.php
<?php

use common\models\LoginForm;
use kartik\checkbox\CheckboxX;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $model LoginForm */
/* @var $this \yii\web\View */
/* @var $form ActiveForm */
?>

<div class="login-box">
    <div class="login-logo">
        <div style="float: left; width: 100%;">
            <img src='img/jmg_logo.png' style="width: 70%;"/>
        </div>
    </div>
    <div class="login-box-body">
        <p class="login-box-msg"><b>Control de Acceso</b></p>
        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
        <div class="form-group has-feedback">
            <?= $form->field($model, 'username')->textInput(['autofocus' => true, 'class' => 'form-control', 'placeholder' => 'Usuario']); ?>
            <span style="top: 25px !important;" class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
            <?= $form->field($model, 'password')->passwordInput(['class' => 'form-control', 'placeholder' => 'Contraseña']) ?>
            <span style="top: 25px !important;" class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>
        <div class="form-group">
            <?php echo $form->field($model, 'rememberMe')->widget(CheckboxX::classname(), [
                'pluginOptions' => ['threeState' => false],
            ])->label('Recuérdame'); ?>
        </div>
        <div class="row">
            <div class="col-xs-4" style="width: 100%">
                <?= Html::submitButton('Iniciar Sesión', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

<script type='text/javascript'>
    document.getElementById("login-form").onsubmit = function (e) {
    };
</script>